sudo: required
services:
- docker

language: java
jdk:
- oraclejdk8

env:
  global:
  - secure: lv6Mx0n1iw6UlqoFD5OYMrGZJtt/e+H+YVI3A5YHwT9SN5XhAhH4KLtcKwSUfVvBN/q/zWzkBik6UoFYANVHPrSiq27NoK2k1IP6emK9YX/+QgDhvpYjhP7kmkm30QbVPCkmVLDu50T2T+TYpyGcPMowz3XG0HD50sfG7wN4EE5QtCu6HtKqVSxz8BQ4hqfpsskRh2OmJpFRvHqytXcsM1JFIa04IvHTHoLIf1+bq2JkptptJLSKDsswBB8fLMGtWA2GtrGjz5W9ggA0jnCPjV4+UNPdcp+tq41KeUKUJedu40IRm4xJukrlid/YQDOp/ySeZwzjuEdCOiXnSpFfSqML6ahE1AHO7OpObNG8tFx+JIoe4QofCqqy/q5tVPiA6aDIVbZo1J8KJPVMH++srudNamSC4J0la050gWxcJ2MCFNWKw+fR2SqmKhr+iCwjNgToLKNEhrSkImoGlHf3Q8OZqFPb1vOaZSQL+p5+mlnTr7r8mKff6ynQihHSGrvky0Bkigh9RcIRNCXIzLS40sSKQffGCOko+JAjAjPydFuBv3CuOWAX2b1o9U2VKdL9LXJYh1rmxrBRAkVstRfUPiiQK+yPUVESnLS+psu+2Ruj2byjW9eLBaPZGA0q1bhy3QryY4jFooTteyTGW6QkY+x17uGnbcaTj43X1CzsbMw=
  - secure: DyGt57il/iTKPqZ/ESkAf17nqikO8CIxASBWTw3Iq45AbmiG0PPSUT/wLqdIlj7OqBIy3bF3x3itzP8705cUF3i6gUxKIxMc7i/Z87bd/VOAizBxHPAEj53WBl5/wpB+se+Mm0UenmbdWgDwomnKaRvBX1/dHWqB1Y45TLbWkaeQjsE2wlaVtebZAvyHRCEJQdLbb5/KdzYNvJFqivTZnXnZVF8cPl5NjPCsvS+cUHENiaayHSeoRZ3TBtQpmScwVKj1lYcNeHwboPWNFM46HVlTHCRJwJW6CC0v+y95jZQVyhTJZW5ar8uZf7rm7sNAwrWG98h7bJHRI6oFYOLdi49ddW4JD2FnZVMYU6B//7Df/3YStbIiLPNKih4cbE1aTr4xQ0FkJJRI76g6c6DX3SIsRKjc0KRfMGjyfV7VrpKsQCeze6pt0ieARBuKd3T94ifDXoXA4QJ2j9pgZareULgu/QeMI4zLmMO5XevpYJDW7UFbOHbfJGkO1ka6ZbkhPMeiFQn15KhiCcrtrYuNDrLllyiu1FckDpxbuFYDPHBzbrJ/Ajk/wS1FlOBYN8uSjObiy52vKiBF1QMcT3P6jmmKpyZvdsJ+VcuFqCYy6b3mq2px9ULIJK/wpKdsc0BL1O5pRa1JqRpuoX1pUKIebapKGxkR4ANl25XxFBDmB/M=

cache:
  directories:
  - "$HOME/.m2"

script:
- mvn clean install

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push shboland/inventory-service
