spring.profiles.active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3382/userDB
    username: root
    password: mysqlpass
    platform: mysql
security:
  user:
    password: password
  enable-csrf: false
  ignored: /resources/**
logging.level.org.springframework.security: DEBUG
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
eureka:
  client:
    enabled: false
---
spring:
  profiles: production
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://mysql:3382/userDB
    username: root
    password: dbpass
security:
  user:
    password: password
  enable-csrf: false
  ignored: /resources/**
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
